# Generated by Django 4.0.3 on 2022-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='who_member',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
