# Generated by Django 4.0.3 on 2022-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price_item',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='text_item',
            field=models.TextField(null=True),
        ),
    ]
