# Generated by Django 4.0.3 on 2022-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_items_info_alter_items_price_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price_item',
            field=models.FloatField(null=True),
        ),
    ]
