# Generated by Django 4.0.3 on 2022-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_items_photo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='text_item',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
