# Generated by Django 4.0.3 on 2022-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_items_text_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='photo_item',
            field=models.ImageField(null=True, upload_to='../media/'),
        ),
    ]
