# Generated by Django 4.0.3 on 2022-05-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_items_photo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='avail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('bots', 'bots'), ('androidapp', 'androidapp'), ('scripts', 'scripts'), ('sitesandweb', 'sitesandweb')], default='sitesandweb', max_length=50),
        ),
    ]
