# Generated by Django 4.0.3 on 2022-05-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_items_avail_alter_items_choice_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='info',
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('androidapp', 'Мобильные приложения для андроид'), ('scripts', 'Скрипты'), ('bots', 'Онлайн боты'), ('sitesandweb', 'Сайты/Веб-приложения')], default='sitesandweb', max_length=50),
        ),
    ]
