# Generated by Django 4.0.3 on 2022-05-09 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_items_info_alter_items_choice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('scripts', 'Скрипты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('androidapp', 'Мобильные приложения для андроид'), ('bots', 'Онлайн боты')], default='sitesandweb', max_length=50),
        ),
    ]
