# Generated by Django 4.0.3 on 2022-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_items_four_photo_item_items_tree_photo_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='privatekey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='seed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('scripts', 'Скрипты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('bots', 'Онлайн боты'), ('androidapp', 'Мобильные приложения для андроид')], default='sitesandweb', max_length=50),
        ),
    ]
