# Generated by Django 4.0.3 on 2022-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_users_address_users_privatekey_users_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('sitesandweb', 'Сайты/Веб-приложения'), ('bots', 'Онлайн боты'), ('scripts', 'Скрипты'), ('androidapp', 'Мобильные приложения для андроид')], default='sitesandweb', max_length=50),
        ),
    ]
