# Generated by Django 4.0.3 on 2022-05-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_items_choice_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('bots', 'Онлайн боты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('scripts', 'Скрипты'), ('androidapp', 'Мобильные приложения для андроид')], default='sitesandweb', max_length=50),
        ),
    ]
