# Generated by Django 4.0.3 on 2022-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_items_choice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='archive_file',
            field=models.FileField(null=True, upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('androidapp', 'Мобильные приложения для Android'), ('sitesandweb', 'Сайты/Веб-приложения'), ('bots', 'Онлайн боты'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('desktopsoft', 'Десктоп софт'), ('treedmodels', '3D модели'), ('scripts', 'Скрипты')], default='sitesandweb', max_length=50),
        ),
    ]
