# Generated by Django 4.0.3 on 2022-05-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_items_archive_file_alter_items_choice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='file_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('treedmodels', '3D модели'), ('desktopsoft', 'Десктоп софт'), ('bots', 'Онлайн боты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('scripts', 'Скрипты'), ('logotype', 'Логотипы'), ('androidapp', 'Мобильные приложения для Android'), ('frontendtamplate', 'html/css/js Frontend Шаблоны')], default='sitesandweb', max_length=50),
        ),
    ]
