# Generated by Django 4.0.3 on 2022-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_items_file_link_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('bots', 'Онлайн боты'), ('androidapp', 'Мобильные приложения для Android'), ('sitesandweb', 'Сайты/Веб-приложения'), ('treedmodels', '3D модели'), ('desktopsoft', 'Десктоп софт'), ('scripts', 'Скрипты')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='file_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='four_photo_item',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='tree_photo_item',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='two_photo_item',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
