# Generated by Django 4.0.3 on 2022-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_items_choice_group_alter_items_file_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='archive_file',
            field=models.FileField(blank=True, null=True, upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('treedmodels', '3D модели'), ('sitesandweb', 'Сайты/Веб-приложения'), ('desktopsoft', 'Десктоп софт'), ('androidapp', 'Мобильные приложения для Android'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('scripts', 'Скрипты'), ('logotype', 'Логотипы'), ('bots', 'Онлайн боты')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='file_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
