# Generated by Django 4.0.3 on 2022-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='archive_file',
            field=models.FileField(null=True, upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('treedmodels', '3D модели'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('scripts', 'Скрипты'), ('androidapp', 'Мобильные приложения для Android'), ('bots', 'Онлайн боты'), ('desktopsoft', 'Десктоп софт'), ('sitesandweb', 'Сайты/Веб-приложения'), ('logotype', 'Логотипы')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='file_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
