# Generated by Django 4.0.3 on 2022-05-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_alter_items_archive_file_alter_items_choice_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='archive_file',
            field=models.FileField(blank=True, null=True, upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('bots', 'Онлайн боты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('androidapp', 'Мобильные приложения для Android'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('logotype', 'Логотипы'), ('scripts', 'Скрипты'), ('desktopsoft', 'Десктоп софт'), ('treedmodels', '3D модели')], default='sitesandweb', max_length=50),
        ),
    ]
