# Generated by Django 4.0.3 on 2022-05-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_items_archive_file_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('sitesandweb', 'Сайты/Веб-приложения'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('treedmodels', '3D модели'), ('androidapp', 'Мобильные приложения для Android'), ('bots', 'Онлайн боты'), ('logotype', 'Логотипы'), ('desktopsoft', 'Десктоп софт'), ('scripts', 'Скрипты')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='file_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
