# Generated by Django 4.0.3 on 2022-05-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_items_datetime_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('treedmodels', '3D модели'), ('desktopsoft', 'Десктоп софт'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('androidapp', 'Мобильные приложения для Android'), ('scripts', 'Скрипты'), ('logotype', 'Логотипы'), ('sitesandweb', 'Сайты/Веб-приложения'), ('bots', 'Онлайн боты')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time'),
        ),
    ]
