# Generated by Django 4.0.3 on 2022-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_items_choice_group_alter_items_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='datetime',
            new_name='datatime',
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('sitesandweb', 'Сайты/Веб-приложения'), ('scripts', 'Скрипты'), ('logotype', 'Логотипы'), ('bots', 'Онлайн боты'), ('desktopsoft', 'Десктоп софт'), ('treedmodels', '3D модели'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('androidapp', 'Мобильные приложения для Android')], default='sitesandweb', max_length=50),
        ),
    ]
