# Generated by Django 4.0.3 on 2022-05-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_rename_datetime_items_datatime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-datatime']},
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('bots', 'Онлайн боты'), ('scripts', 'Скрипты'), ('desktopsoft', 'Десктоп софт'), ('logotype', 'Логотипы'), ('androidapp', 'Мобильные приложения для Android'), ('treedmodels', '3D модели'), ('sitesandweb', 'Сайты/Веб-приложения')], default='sitesandweb', max_length=50),
        ),
    ]
