# Generated by Django 4.0.3 on 2022-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_alter_items_options_alter_items_choice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar_profile',
            field=models.ImageField(null=True, upload_to='media/avatar'),
        ),
        migrations.AddField(
            model_name='users',
            name='background_profile',
            field=models.ImageField(null=True, upload_to='media/avatar'),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('treedmodels', '3D модели'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('bots', 'Онлайн боты'), ('desktopsoft', 'Десктоп софт'), ('logotype', 'Логотипы'), ('sitesandweb', 'Сайты/Веб-приложения'), ('scripts', 'Скрипты'), ('androidapp', 'Мобильные приложения для Android')], default='sitesandweb', max_length=50),
        ),
    ]
