# Generated by Django 4.0.3 on 2022-05-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_users_avatar_profile_users_background_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('bots', 'Онлайн боты'), ('logotype', 'Логотипы'), ('treedmodels', '3D модели'), ('sitesandweb', 'Сайты/Веб-приложения'), ('androidapp', 'Мобильные приложения для Android'), ('scripts', 'Скрипты'), ('desktopsoft', 'Десктоп софт')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatar'),
        ),
        migrations.AlterField(
            model_name='users',
            name='background_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatar'),
        ),
        migrations.AlterField(
            model_name='users',
            name='who_member',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
