# Generated by Django 4.0.3 on 2022-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_alter_items_choice_group_alter_users_avatar_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('sitesandweb', 'Сайты/Веб-приложения'), ('androidapp', 'Мобильные приложения для Android'), ('desktopsoft', 'Десктоп софт'), ('logotype', 'Логотипы'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('treedmodels', '3D модели'), ('scripts', 'Скрипты'), ('bots', 'Онлайн боты')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar_profile',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='background_profile',
            field=models.ImageField(blank=True, null=True, upload_to='avatarback/'),
        ),
    ]
