# Generated by Django 4.0.3 on 2022-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_alter_items_choice_group_alter_users_avatar_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('scripts', 'Скрипты'), ('logotype', 'Логотипы'), ('sitesandweb', 'Сайты/Веб-приложения'), ('treedmodels', '3D модели'), ('androidapp', 'Мобильные приложения для Android'), ('bots', 'Онлайн боты'), ('desktopsoft', 'Десктоп софт'), ('frontendtamplate', 'html/css/js Frontend Шаблоны')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar_profile',
            field=models.ImageField(blank=True, default='avatar/person.png', null=True, upload_to='avatar/'),
        ),
    ]
