# Generated by Django 4.0.3 on 2022-05-13 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_alter_items_choice_group_alter_users_avatar_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='avatar_profile',
        ),
        migrations.RemoveField(
            model_name='users',
            name='background_profile',
        ),
        migrations.RemoveField(
            model_name='users',
            name='who_member',
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('androidapp', 'Мобильные приложения для Android'), ('scripts', 'Скрипты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('desktopsoft', 'Десктоп софт'), ('treedmodels', '3D модели'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('bots', 'Онлайн боты'), ('logotype', 'Логотипы')], default='sitesandweb', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('who_member', models.CharField(blank=True, max_length=60, null=True)),
                ('avatar_profile', models.ImageField(blank=True, default='avatar/person.png', null=True, upload_to='avatar/')),
                ('background_profile', models.ImageField(blank=True, null=True, upload_to='avatarback/default_back.png')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
