# Generated by Django 4.0.3 on 2022-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_alter_items_choice_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('sitesandweb', 'Сайты/Веб-приложения'), ('logotype', 'Логотипы'), ('treedmodels', '3D модели'), ('bots', 'Онлайн боты'), ('androidapp', 'Мобильные приложения для Android'), ('scripts', 'Скрипты'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('desktopsoft', 'Десктоп софт')], default='sitesandweb', max_length=50),
        ),
    ]
