# Generated by Django 4.0.3 on 2022-05-13 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_remove_profile_username_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('androidapp', 'Мобильные приложения для Android'), ('desktopsoft', 'Десктоп софт'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('sitesandweb', 'Сайты/Веб-приложения'), ('treedmodels', '3D модели'), ('scripts', 'Скрипты'), ('bots', 'Онлайн боты')], default='sitesandweb', max_length=50),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
