# Generated by Django 4.0.3 on 2022-05-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_alter_items_choice_group_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('bots', 'Онлайн боты'), ('treedmodels', '3D модели'), ('desktopsoft', 'Десктоп софт'), ('androidapp', 'Мобильные приложения для Android'), ('logotype', 'Логотипы'), ('scripts', 'Скрипты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('frontendtamplate', 'html/css/js Frontend Шаблоны')], default='sitesandweb', max_length=50),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
