# Generated by Django 4.0.3 on 2022-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_alter_items_choice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar_profile',
            field=models.ImageField(blank=True, default='avatar/person.png', null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='users',
            name='background_profile',
            field=models.ImageField(blank=True, null=True, upload_to='avatarback/default_back.png'),
        ),
        migrations.AddField(
            model_name='users',
            name='who_member',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('bots', 'Онлайн боты'), ('sitesandweb', 'Сайты/Веб-приложения'), ('treedmodels', '3D модели'), ('androidapp', 'Мобильные приложения для Android'), ('logotype', 'Логотипы'), ('desktopsoft', 'Десктоп софт'), ('scripts', 'Скрипты')], default='sitesandweb', max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
