# Generated by Django 4.0.3 on 2022-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_users_avatar_profile_users_background_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('androidapp', 'Мобильные приложения для Android'), ('bots', 'Онлайн боты'), ('treedmodels', '3D модели'), ('desktopsoft', 'Десктоп софт'), ('scripts', 'Скрипты'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('logotype', 'Логотипы'), ('sitesandweb', 'Сайты/Веб-приложения')], default='sitesandweb', max_length=50),
        ),
    ]
