# Generated by Django 4.0.3 on 2022-05-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_users_purchases_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('androidapp', 'Мобильные приложения для Android'), ('treedmodels', '3D модели'), ('sitesandweb', 'Сайты/Веб-приложения'), ('scripts', 'Скрипты'), ('bots', 'Онлайн боты'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('desktopsoft', 'Десктоп софт')], default='sitesandweb', max_length=50),
        ),
        migrations.RemoveField(
            model_name='users',
            name='purchases',
        ),
        migrations.AddField(
            model_name='users',
            name='purchases',
            field=models.ManyToManyField(null=True, to='web.items'),
        ),
    ]
