# Generated by Django 4.0.3 on 2022-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_alter_items_choice_group_remove_users_purchases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('bots', 'Онлайн боты'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('treedmodels', '3D модели'), ('logotype', 'Логотипы'), ('androidapp', 'Мобильные приложения для Android'), ('sitesandweb', 'Сайты/Веб-приложения'), ('desktopsoft', 'Десктоп софт'), ('scripts', 'Скрипты')], default='sitesandweb', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='purchases',
            field=models.ManyToManyField(to='web.items'),
        ),
    ]
