# Generated by Django 4.0.3 on 2022-05-20 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_alter_items_choice_group_alter_users_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='purchases',
        ),
        migrations.AddField(
            model_name='items',
            name='orders_buyers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='items',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('bots', 'Онлайн боты'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('scripts', 'Скрипты'), ('treedmodels', '3D модели'), ('androidapp', 'Мобильные приложения для Android'), ('sitesandweb', 'Сайты/Веб-приложения'), ('logotype', 'Логотипы'), ('desktopsoft', 'Десктоп софт')], default='sitesandweb', max_length=50),
        ),
    ]
