# Generated by Django 4.0.3 on 2022-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_remove_users_purchases_items_orders_buyers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='uu_id',
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('androidapp', 'Мобильные приложения для Android'), ('bots', 'Онлайн боты'), ('scripts', 'Скрипты'), ('treedmodels', '3D модели'), ('desktopsoft', 'Десктоп софт'), ('sitesandweb', 'Сайты/Веб-приложения'), ('frontendtamplate', 'html/css/js Frontend Шаблоны')], default='sitesandweb', max_length=50),
        ),
    ]
