# Generated by Django 4.0.3 on 2022-05-30 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('sitesandweb', 'Сайты/Веб-приложения'), ('androidapp', 'Мобильные приложения для Android'), ('scripts', 'Скрипты'), ('bots', 'Онлайн боты'), ('treedmodels', '3D модели'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('desktopsoft', 'Десктоп софт'), ('courses', 'Обучающие курсы'), ('books', 'Электронные книги')], default='sitesandweb', max_length=50),
        ),
        migrations.CreateModel(
            name='CloudFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=500, null=True)),
                ('total_size', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='media/CloudFiles/')),
                ('datatime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time')),
                ('author_files', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datatime'],
            },
        ),
    ]
