# Generated by Django 4.0.3 on 2022-06-02 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_alter_items_choice_group_cloudfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('courses', 'Обучающие курсы'), ('scripts', 'Скрипты'), ('logotype', 'Логотипы'), ('bots', 'Онлайн боты'), ('desktopsoft', 'Десктоп софт'), ('treedmodels', '3D модели'), ('books', 'Электронные книги'), ('sitesandweb', 'Сайты/Веб-приложения'), ('androidapp', 'Мобильные приложения для Android')], default='sitesandweb', max_length=50),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=30)),
                ('password_folder', models.CharField(blank=True, max_length=50, null=True)),
                ('author_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
