# Generated by Django 4.0.3 on 2022-06-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_alter_items_choice_group_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfiles',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder',
            field=models.CharField(max_length=30, verbose_name='Название диска'),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('books', 'Электронные книги'), ('sitesandweb', 'Сайты/Веб-приложения'), ('courses', 'Обучающие курсы'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('androidapp', 'Мобильные приложения для Android'), ('scripts', 'Скрипты'), ('treedmodels', '3D модели'), ('desktopsoft', 'Десктоп софт'), ('logotype', 'Логотипы'), ('bots', 'Онлайн боты')], default='sitesandweb', max_length=50),
        ),
    ]
