# Generated by Django 4.0.3 on 2022-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_cloudfiles_folder_alter_folder_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('books', 'Электронные книги'), ('desktopsoft', 'Десктоп софт'), ('scripts', 'Скрипты'), ('courses', 'Обучающие курсы'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('treedmodels', '3D модели'), ('bots', 'Онлайн боты'), ('androidapp', 'Мобильные приложения для Android'), ('sitesandweb', 'Сайты/Веб-приложения')], default='sitesandweb', max_length=50),
        ),
    ]
