# Generated by Django 4.0.3 on 2022-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='password_folder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('logotype', 'Логотипы'), ('desktopsoft', 'Десктоп софт'), ('treedmodels', '3D модели'), ('androidapp', 'Мобильные приложения для Android'), ('sitesandweb', 'Сайты/Веб-приложения'), ('bots', 'Онлайн боты'), ('scripts', 'Скрипты'), ('courses', 'Обучающие курсы'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('books', 'Электронные книги')], default='sitesandweb', max_length=50),
        ),
    ]
