# Generated by Django 4.0.3 on 2022-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_alter_items_choice_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('datatime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time')),
            ],
            options={
                'ordering': ['-datatime'],
            },
        ),
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('scripts', 'Скрипты'), ('logotype', 'Логотипы'), ('bots', 'Онлайн боты'), ('books', 'Электронные книги'), ('treedmodels', '3D модели'), ('androidapp', 'Мобильные приложения для Android'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('courses', 'Обучающие курсы'), ('desktopsoft', 'Десктоп софт'), ('sitesandweb', 'Сайты/Веб-приложения')], default='sitesandweb', max_length=50),
        ),
    ]
