# Generated by Django 4.1 on 2022-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_news_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('treedmodels', '3D модели'), ('scripts', 'Скрипты'), ('books', 'Электронные книги'), ('logotype', 'Логотипы'), ('courses', 'Обучающие курсы'), ('bots', 'Онлайн боты'), ('desktopsoft', 'Десктоп софт'), ('sitesandweb', 'Сайты/Веб-приложения'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('androidapp', 'Мобильные приложения для Android')], default='sitesandweb', max_length=50),
        ),
    ]
