# Generated by Django 4.1 on 2022-08-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('androidapp', 'Мобильные приложения для Android'), ('courses', 'Обучающие курсы'), ('treedmodels', '3D модели'), ('books', 'Электронные книги'), ('scripts', 'Скрипты'), ('desktopsoft', 'Десктоп софт'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('sitesandweb', 'Сайты/Веб-приложения'), ('logotype', 'Логотипы'), ('bots', 'Онлайн боты')], default='sitesandweb', max_length=50),
        ),
    ]
