# Generated by Django 4.1 on 2022-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0077_alter_items_choice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choice_group',
            field=models.CharField(choices=[('books', 'Электронные книги'), ('desktopsoft', 'Десктоп софт'), ('frontendtamplate', 'html/css/js Frontend Шаблоны'), ('logotype', 'Логотипы'), ('sitesandweb', 'Сайты/Веб-приложения'), ('treedmodels', '3D модели'), ('courses', 'Обучающие курсы'), ('bots', 'Онлайн боты'), ('scripts', 'Скрипты'), ('androidapp', 'Мобильные приложения для Android')], default='sitesandweb', max_length=50),
        ),
    ]
